# Generated by Django 5.2.7 on 2025-10-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
