# Generated by Django 5.2.7 on 2025-11-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_freelancerprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated list of skills', max_length=500),
        ),
    ]
