# Generated by Django 5.2.7 on 2025-11-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_freelancerprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
